// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * MessageRecord is the database model for a message.
 */
export class MessageRecord {
    /**
     * Creates a new MessageRecord instance.
     * @param {Partial<MessageRecord>} [$$source = {}] - The source object to create the MessageRecord.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("TaskID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TaskID"] = "";
        }
        if (!("Role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Role"] = "";
        }
        if (!("Content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Content"] = "";
        }
        if (!("ReasoningContent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ReasoningContent"] = "";
        }
        if (!("ToolCalls" in $$source)) {
            /**
             * JSON
             * @member
             * @type {string}
             */
            this["ToolCalls"] = "";
        }
        if (!("ToolCallID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ToolCallID"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["CreatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MessageRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageRecord(/** @type {Partial<MessageRecord>} */($$parsedSource));
    }
}

/**
 * TaskRecord is the database model for a task.
 */
export class TaskRecord {
    /**
     * Creates a new TaskRecord instance.
     * @param {Partial<TaskRecord>} [$$source = {}] - The source object to create the TaskRecord.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }
        if (!("Prompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Prompt"] = "";
        }
        if (!("Mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Mode"] = "";
        }
        if (!("Provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Provider"] = "";
        }
        if (!("Model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Model"] = "";
        }
        if (!("Status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Status"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["UpdatedAt"] = null;
        }
        if (!("CompletedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["CompletedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskRecord(/** @type {Partial<TaskRecord>} */($$parsedSource));
    }
}
