// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService exposes chat operations to the Wails front-end.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../internal/storage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnswerFollowupQuestion sends the user's answer back to a pending AskFollowupQuestion call.
 * @param {string} answer
 * @returns {$CancellablePromise<void>}
 */
export function AnswerFollowupQuestion(answer) {
    return $Call.ByID(1944089549, answer);
}

/**
 * BuildHelpText returns formatted help for slash commands.
 * @returns {$CancellablePromise<string>}
 */
export function BuildHelpText() {
    return $Call.ByID(711945389);
}

/**
 * CompactConversation triggers manual compaction of the conversation history.
 * @returns {$CancellablePromise<boolean>}
 */
export function CompactConversation() {
    return $Call.ByID(3517242699);
}

/**
 * DeleteTask deletes a task and its messages
 * @param {string} taskID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTask(taskID) {
    return $Call.ByID(2653465909, taskID);
}

/**
 * ExecuteSlashCommand runs a slash command and returns the result.
 * @param {string} name
 * @param {string} args
 * @returns {$CancellablePromise<$models.SlashActionResult | null>}
 */
export function ExecuteSlashCommand(name, args) {
    return $Call.ByID(2115491496, name, args).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * FilterSlashCommands returns commands matching the given prefix.
 * @param {string} prefix
 * @returns {$CancellablePromise<$models.SlashCommandInfo[]>}
 */
export function FilterSlashCommands(prefix) {
    return $Call.ByID(1206819056, prefix).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetConfig returns the current configuration
 * @returns {$CancellablePromise<string>}
 */
export function GetConfig() {
    return $Call.ByID(889101375);
}

/**
 * GetConversationState returns the current messages in JSON form.
 * @returns {$CancellablePromise<string>}
 */
export function GetConversationState() {
    return $Call.ByID(2856922691);
}

/**
 * GetMode returns the current agent mode ("plan" or "act").
 * @returns {$CancellablePromise<string>}
 */
export function GetMode() {
    return $Call.ByID(371492154);
}

/**
 * GetSlashCommands returns all available slash commands.
 * @returns {$CancellablePromise<$models.SlashCommandInfo[]>}
 */
export function GetSlashCommands() {
    return $Call.ByID(2712373680).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetStatus returns current provider, model, working directory, mode and token usage.
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetStatus() {
    return $Call.ByID(4059966519).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetTaskSummary returns a task with its messages
 * @param {string} taskID
 * @returns {$CancellablePromise<[storage$0.TaskRecord | null, storage$0.MessageRecord[]]>}
 */
export function GetTaskSummary(taskID) {
    return $Call.ByID(3884067532, taskID).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType6($result[0]);
        $result[1] = $$createType8($result[1]);
        return $result;
    }));
}

/**
 * InitSlashRegistry initialises the slash command registry for this service.
 * @returns {$CancellablePromise<void>}
 */
export function InitSlashRegistry() {
    return $Call.ByID(1139163529);
}

/**
 * IsSlashCommand checks if text is a standalone slash command.
 * @param {string} text
 * @returns {$CancellablePromise<boolean>}
 */
export function IsSlashCommand(text) {
    return $Call.ByID(4200936369, text);
}

/**
 * ListTasks returns conversation history
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<storage$0.TaskRecord[]>}
 */
export function ListTasks(limit, offset) {
    return $Call.ByID(2917519979, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * LoadTask restores agent state for an existing task.
 * @param {string} taskID
 * @returns {$CancellablePromise<storage$0.TaskRecord | null>}
 */
export function LoadTask(taskID) {
    return $Call.ByID(3581714498, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * NewConversation resets the agent for a new conversation.
 * Reset the conversation (used by frontend when user clicks New Chat), no dialog.
 * @returns {$CancellablePromise<void>}
 */
export function NewConversation() {
    return $Call.ByID(1999326860);
}

/**
 * ParseSlashCommand extracts name and args from slash text.
 * @param {string} text
 * @returns {$CancellablePromise<[string, string]>}
 */
export function ParseSlashCommand(text) {
    return $Call.ByID(34237656, text);
}

/**
 * SelectProjectDir opens a directory picker and sets the working directory without resetting conversation.
 * If a task is currently active, it also updates the task's working_dir in the database.
 * @returns {$CancellablePromise<string>}
 */
export function SelectProjectDir() {
    return $Call.ByID(623065575);
}

/**
 * @param {string} prompt
 * @returns {$CancellablePromise<void>}
 */
export function SendMessage(prompt) {
    return $Call.ByID(1063940756, prompt);
}

/**
 * SetApp sets the application reference (called after app creation).
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(893176384, app);
}

/**
 * SetMode switches the agent between plan and act modes.
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetMode(mode) {
    return $Call.ByID(663171742, mode);
}

/**
 * StartNewConversation resets the conversation and clears the selected project directory.
 * @returns {$CancellablePromise<void>}
 */
export function StartNewConversation() {
    return $Call.ByID(262799438);
}

/**
 * StopMessage aborts the current agent run.
 * @returns {$CancellablePromise<void>}
 */
export function StopMessage() {
    return $Call.ByID(1744506322);
}

/**
 * UpdateConfig updates a config key
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function UpdateConfig(key, value) {
    return $Call.ByID(4274389964, key, value);
}

// Private type creation functions
const $$createType0 = $models.SlashActionResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.SlashCommandInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = storage$0.TaskRecord.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = storage$0.MessageRecord.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($$createType5);
