// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService exposes chat operations to the Wails front-end.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as prompts$0 from "../internal/prompts/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../internal/storage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnswerFollowupQuestion sends the user's answer back to a pending AskFollowupQuestion call.
 */
export function AnswerFollowupQuestion(answer: string): $CancellablePromise<void> {
    return $Call.ByID(1944089549, answer);
}

/**
 * BuildHelpText returns formatted help for slash commands.
 */
export function BuildHelpText(): $CancellablePromise<string> {
    return $Call.ByID(711945389);
}

/**
 * CompactConversation triggers manual compaction of the conversation history.
 */
export function CompactConversation(): $CancellablePromise<boolean> {
    return $Call.ByID(3517242699);
}

/**
 * DeleteTask deletes a task and its messages
 */
export function DeleteTask(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2653465909, taskID);
}

/**
 * ExecuteSlashCommand runs a slash command and returns the result.
 */
export function ExecuteSlashCommand(name: string, args: string): $CancellablePromise<$models.SlashActionResult | null> {
    return $Call.ByID(2115491496, name, args).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * FilterSlashCommands returns commands matching the given prefix.
 */
export function FilterSlashCommands(prefix: string): $CancellablePromise<$models.SlashCommandInfo[]> {
    return $Call.ByID(1206819056, prefix).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetConfig returns the current configuration
 */
export function GetConfig(): $CancellablePromise<string> {
    return $Call.ByID(889101375);
}

/**
 * GetConversationState returns the current messages in JSON form.
 */
export function GetConversationState(): $CancellablePromise<string> {
    return $Call.ByID(2856922691);
}

/**
 * GetMode returns the current agent mode ("plan" or "act").
 */
export function GetMode(): $CancellablePromise<string> {
    return $Call.ByID(371492154);
}

/**
 * GetRulesInfo returns metadata about available custom rule files.
 */
export function GetRulesInfo(): $CancellablePromise<prompts$0.RuleFileInfo[]> {
    return $Call.ByID(2145237972).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetSlashCommands returns all available slash commands.
 */
export function GetSlashCommands(): $CancellablePromise<$models.SlashCommandInfo[]> {
    return $Call.ByID(2712373680).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetStatus returns current provider, model, working directory, mode and token usage.
 */
export function GetStatus(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(4059966519).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetTaskSummary returns a task with its messages
 */
export function GetTaskSummary(taskID: string): $CancellablePromise<[storage$0.TaskRecord | null, storage$0.MessageRecord[]]> {
    return $Call.ByID(3884067532, taskID).then(($result: any) => {
        $result[0] = $$createType8($result[0]);
        $result[1] = $$createType10($result[1]);
        return $result;
    });
}

/**
 * InitSlashRegistry initialises the slash command registry for this service.
 */
export function InitSlashRegistry(): $CancellablePromise<void> {
    return $Call.ByID(1139163529);
}

/**
 * IsSlashCommand checks if text is a standalone slash command.
 */
export function IsSlashCommand(text: string): $CancellablePromise<boolean> {
    return $Call.ByID(4200936369, text);
}

/**
 * ListDirEntries returns files and subdirectories under the given relative path.
 * dirPath is relative to the project's working directory; empty string means root.
 */
export function ListDirEntries(dirPath: string): $CancellablePromise<$models.DirEntry[]> {
    return $Call.ByID(1442448370, dirPath).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * ListTasks returns conversation history
 */
export function ListTasks(limit: number, offset: number): $CancellablePromise<storage$0.TaskRecord[]> {
    return $Call.ByID(2917519979, limit, offset).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * LoadTask restores agent state for an existing task.
 */
export function LoadTask(taskID: string): $CancellablePromise<storage$0.TaskRecord | null> {
    return $Call.ByID(3581714498, taskID).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * NewConversation resets the agent for a new conversation.
 * Reset the conversation (used by frontend when user clicks New Chat), no dialog.
 */
export function NewConversation(): $CancellablePromise<void> {
    return $Call.ByID(1999326860);
}

/**
 * ParseSlashCommand extracts name and args from slash text.
 */
export function ParseSlashCommand(text: string): $CancellablePromise<[string, string]> {
    return $Call.ByID(34237656, text);
}

/**
 * ReadFileContent reads a file's content relative to the working directory.
 * Returns the file content as a string. Binary files are detected and skipped.
 * Files larger than maxFileReadSize are truncated.
 */
export function ReadFileContent(relPath: string): $CancellablePromise<string> {
    return $Call.ByID(2901970126, relPath);
}

/**
 * ReloadRules reloads custom rules from disk and updates the agent.
 * Returns the number of rule files loaded and a formatted description.
 */
export function ReloadRules(): $CancellablePromise<[number, string]> {
    return $Call.ByID(3702964733);
}

/**
 * SelectProjectDir opens a directory picker and sets the working directory without resetting conversation.
 * If a task is currently active, it also updates the task's working_dir in the database.
 */
export function SelectProjectDir(): $CancellablePromise<string> {
    return $Call.ByID(623065575);
}

export function SendMessage(prompt: string): $CancellablePromise<void> {
    return $Call.ByID(1063940756, prompt);
}

/**
 * SendMessageWithContext sends a message with file references attached.
 * fileRefsJSON is a JSON array of relative file paths, e.g. ["src/main.go","README.md"].
 * The referenced file contents are read and prepended to the prompt as context.
 */
export function SendMessageWithContext(prompt: string, fileRefsJSON: string): $CancellablePromise<void> {
    return $Call.ByID(3385566703, prompt, fileRefsJSON);
}

/**
 * SetApp sets the application reference (called after app creation).
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(893176384, app);
}

/**
 * SetMode switches the agent between plan and act modes.
 */
export function SetMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(663171742, mode);
}

/**
 * StartNewConversation resets the conversation and clears the selected project directory.
 */
export function StartNewConversation(): $CancellablePromise<void> {
    return $Call.ByID(262799438);
}

/**
 * StopMessage aborts the current agent run.
 */
export function StopMessage(): $CancellablePromise<void> {
    return $Call.ByID(1744506322);
}

/**
 * UpdateConfig updates a config key
 */
export function UpdateConfig(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(4274389964, key, value);
}

// Private type creation functions
const $$createType0 = $models.SlashActionResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.SlashCommandInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = prompts$0.RuleFileInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
const $$createType7 = storage$0.TaskRecord.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = storage$0.MessageRecord.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.DirEntry.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Array($$createType7);
