// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService exposes chat operations to the Wails front-end.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../internal/storage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * AnswerFollowupQuestion sends the user's answer back to a pending AskFollowupQuestion call.
 */
export function AnswerFollowupQuestion(answer: string): $CancellablePromise<void> {
    return $Call.ByID(1944089549, answer);
}

/**
 * CompactConversation triggers manual compaction of the conversation history.
 */
export function CompactConversation(): $CancellablePromise<boolean> {
    return $Call.ByID(3517242699);
}

/**
 * DeleteTask deletes a task and its messages
 */
export function DeleteTask(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2653465909, taskID);
}

/**
 * GetConfig returns the current configuration
 */
export function GetConfig(): $CancellablePromise<string> {
    return $Call.ByID(889101375);
}

/**
 * GetConversationState returns the current messages in JSON form.
 */
export function GetConversationState(): $CancellablePromise<string> {
    return $Call.ByID(2856922691);
}

/**
 * GetMode returns the current agent mode ("plan" or "act").
 */
export function GetMode(): $CancellablePromise<string> {
    return $Call.ByID(371492154);
}

/**
 * GetStatus returns current provider, model, working directory, mode and token usage.
 */
export function GetStatus(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(4059966519).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetTaskSummary returns a task with its messages
 */
export function GetTaskSummary(taskID: string): $CancellablePromise<[storage$0.TaskRecord | null, storage$0.MessageRecord[]]> {
    return $Call.ByID(3884067532, taskID).then(($result: any) => {
        $result[0] = $$createType2($result[0]);
        $result[1] = $$createType4($result[1]);
        return $result;
    });
}

/**
 * ListTasks returns conversation history
 */
export function ListTasks(limit: number, offset: number): $CancellablePromise<storage$0.TaskRecord[]> {
    return $Call.ByID(2917519979, limit, offset).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * LoadTask restores agent state for an existing task.
 */
export function LoadTask(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(3581714498, taskID);
}

/**
 * NewConversation resets the agent for a new conversation.
 */
export function NewConversation(): $CancellablePromise<void> {
    return $Call.ByID(1999326860);
}

export function SendMessage(prompt: string): $CancellablePromise<void> {
    return $Call.ByID(1063940756, prompt);
}

/**
 * SetApp sets the application reference (called after app creation).
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(893176384, app);
}

/**
 * SetMode switches the agent between plan and act modes.
 */
export function SetMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(663171742, mode);
}

/**
 * StopMessage aborts the current agent run.
 */
export function StopMessage(): $CancellablePromise<void> {
    return $Call.ByID(1744506322);
}

/**
 * UpdateConfig updates a config key
 */
export function UpdateConfig(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(4274389964, key, value);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = storage$0.TaskRecord.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = storage$0.MessageRecord.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($$createType1);
