// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SlashActionResult is returned after executing a slash command.
 */
export class SlashActionResult {
    /**
     * Creates a new SlashActionResult instance.
     * @param {Partial<SlashActionResult>} [$$source = {}] - The source object to create the SlashActionResult.
     */
    constructor($$source = {}) {
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SlashActionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SlashActionResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SlashActionResult(/** @type {Partial<SlashActionResult>} */($$parsedSource));
    }
}

/**
 * SlashCommandInfo holds serializable metadata for a slash command.
 */
export class SlashCommandInfo {
    /**
     * Creates a new SlashCommandInfo instance.
     * @param {Partial<SlashCommandInfo>} [$$source = {}] - The source object to create the SlashCommandInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("section" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["section"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SlashCommandInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SlashCommandInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SlashCommandInfo(/** @type {Partial<SlashCommandInfo>} */($$parsedSource));
    }
}
