// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SlashActionResult is returned after executing a slash command.
 */
export class SlashActionResult {
    "action": string;
    "message": string;

    /** Creates a new SlashActionResult instance. */
    constructor($$source: Partial<SlashActionResult> = {}) {
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SlashActionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SlashActionResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SlashActionResult($$parsedSource as Partial<SlashActionResult>);
    }
}

/**
 * SlashCommandInfo holds serializable metadata for a slash command.
 */
export class SlashCommandInfo {
    "name": string;
    "description": string;
    "section": string;

    /** Creates a new SlashCommandInfo instance. */
    constructor($$source: Partial<SlashCommandInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("section" in $$source)) {
            this["section"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SlashCommandInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SlashCommandInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SlashCommandInfo($$parsedSource as Partial<SlashCommandInfo>);
    }
}
