// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DirEntry represents a file or directory entry for the frontend file browser.
 */
export class DirEntry {
    "name": string;
    "path": string;
    "isDir": boolean;
    "size": number;
    "modTime": number;

    /** Creates a new DirEntry instance. */
    constructor($$source: Partial<DirEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DirEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): DirEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DirEntry($$parsedSource as Partial<DirEntry>);
    }
}

/**
 * SlashActionResult is returned after executing a slash command.
 */
export class SlashActionResult {
    "action": string;
    "message": string;

    /** Creates a new SlashActionResult instance. */
    constructor($$source: Partial<SlashActionResult> = {}) {
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SlashActionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SlashActionResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SlashActionResult($$parsedSource as Partial<SlashActionResult>);
    }
}

/**
 * SlashCommandInfo holds serializable metadata for a slash command.
 */
export class SlashCommandInfo {
    "name": string;
    "description": string;
    "section": string;

    /** Creates a new SlashCommandInfo instance. */
    constructor($$source: Partial<SlashCommandInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("section" in $$source)) {
            this["section"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SlashCommandInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SlashCommandInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SlashCommandInfo($$parsedSource as Partial<SlashCommandInfo>);
    }
}

/**
 * MCPServerStatus holds the status of an MCP server.
 */
export class MCPServerStatus {
    "name": string;
    "connected": boolean;
    "initialized": boolean;
    "tools": number;
    "toolNames": string[];
    "lastError": string;

    /** Creates a new MCPServerStatus instance. */
    constructor($$source: Partial<MCPServerStatus> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("initialized" in $$source)) {
            this["initialized"] = false;
        }
        if (!("tools" in $$source)) {
            this["tools"] = 0;
        }
        if (!("toolNames" in $$source)) {
            this["toolNames"] = [];
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPServerStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPServerStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MCPServerStatus($$parsedSource as Partial<MCPServerStatus>);
    }
}
