// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * RuleFileInfo holds metadata about a loaded rule file.
 */
export class RuleFileInfo {
    "name": string;

    /**
     * "global" or "workspace"
     */
    "source": string;

    /**
     * file size in bytes
     */
    "size": number;

    /**
     * unix timestamp (seconds)
     */
    "modTime": number;

    /** Creates a new RuleFileInfo instance. */
    constructor($$source: Partial<RuleFileInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuleFileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RuleFileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuleFileInfo($$parsedSource as Partial<RuleFileInfo>);
    }
}
