// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService exposes chat operations to the Wails front-end.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as prompts$0 from "../prompts/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnswerFollowupQuestion sends the user's answer back to a pending AskFollowupQuestion call.
 */
export function AnswerFollowupQuestion(answer: string): $CancellablePromise<void> {
    return $Call.ByID(2763467677, answer);
}

/**
 * BuildHelpText returns formatted help for slash commands.
 */
export function BuildHelpText(): $CancellablePromise<string> {
    return $Call.ByID(1706870077);
}

/**
 * ClearConversation clears the conversation and resets the task,
 * but preserves the working directory so the user stays in the same project.
 * Used by /clear slash command.
 */
export function ClearConversation(): $CancellablePromise<void> {
    return $Call.ByID(1733260091);
}

/**
 * CompactConversation triggers manual compaction of the conversation history.
 */
export function CompactConversation(): $CancellablePromise<boolean> {
    return $Call.ByID(4150294459);
}

/**
 * DeleteTask deletes a task and its messages
 */
export function DeleteTask(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2816975205, taskID);
}

/**
 * ExecuteSlashCommand runs a slash command and returns the result.
 */
export function ExecuteSlashCommand(name: string, args: string): $CancellablePromise<$models.SlashActionResult | null> {
    return $Call.ByID(2920061560, name, args).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * FilterSlashCommands returns commands matching the given prefix.
 */
export function FilterSlashCommands(prefix: string): $CancellablePromise<$models.SlashCommandInfo[]> {
    return $Call.ByID(712799040, prefix).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetConfig returns the current configuration
 */
export function GetConfig(): $CancellablePromise<string> {
    return $Call.ByID(1074815567);
}

/**
 * GetConversationState returns the current messages in JSON form.
 * Messages are truncated to avoid exceeding Wails IPC payload limits.
 */
export function GetConversationState(): $CancellablePromise<string> {
    return $Call.ByID(3454410515);
}

/**
 * GetMode returns the current agent mode ("plan" or "act").
 */
export function GetMode(): $CancellablePromise<string> {
    return $Call.ByID(1926049162);
}

/**
 * GetRulesInfo returns metadata about available custom rule files.
 */
export function GetRulesInfo(): $CancellablePromise<prompts$0.RuleFileInfo[]> {
    return $Call.ByID(1836671012).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetSlashCommands returns all available slash commands.
 */
export function GetSlashCommands(): $CancellablePromise<$models.SlashCommandInfo[]> {
    return $Call.ByID(3443469184).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetStatus returns current provider, model, working directory, mode and token usage.
 */
export function GetStatus(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(769312231).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetTaskSummary returns a task with its messages
 */
export function GetTaskSummary(taskID: string): $CancellablePromise<[storage$0.TaskRecord | null, storage$0.MessageRecord[]]> {
    return $Call.ByID(2564082748, taskID).then(($result: any) => {
        $result[0] = $$createType8($result[0]);
        $result[1] = $$createType10($result[1]);
        return $result;
    });
}

/**
 * InitSlashRegistry initialises the slash command registry for this service.
 */
export function InitSlashRegistry(): $CancellablePromise<void> {
    return $Call.ByID(448534841);
}

/**
 * IsSlashCommand checks if text is a standalone slash command.
 */
export function IsSlashCommand(text: string): $CancellablePromise<boolean> {
    return $Call.ByID(387659809, text);
}

/**
 * KBCreate creates a new knowledge base.
 */
export function KBCreate(name: string, description: string, kbType: string): $CancellablePromise<string> {
    return $Call.ByID(1003922426, name, description, kbType);
}

/**
 * KBIngestFile ingests a file (e.g. PDF, DOCX, MD) into a knowledge base.
 * Only performs RAG ingestion (chunk + embed + store).
 */
export function KBIngestFile(kbNameOrID: string, filePath: string): $CancellablePromise<void> {
    return $Call.ByID(2399687764, kbNameOrID, filePath);
}

/**
 * KBList returns the list of knowledge bases as a JSON string.
 */
export function KBList(): $CancellablePromise<string> {
    return $Call.ByID(4035429994);
}

/**
 * ListDirEntries returns files and subdirectories under the given relative path.
 * dirPath is relative to the project's working directory; empty string means root.
 */
export function ListDirEntries(dirPath: string): $CancellablePromise<$models.DirEntry[]> {
    return $Call.ByID(3326127938, dirPath).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * ListTasks returns conversation history
 */
export function ListTasks(limit: number, offset: number): $CancellablePromise<storage$0.TaskRecord[]> {
    return $Call.ByID(2963132795, limit, offset).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * LoadTask restores agent state for an existing task.
 */
export function LoadTask(taskID: string): $CancellablePromise<storage$0.TaskRecord | null> {
    return $Call.ByID(183112338, taskID).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ParseSlashCommand extracts name and args from slash text.
 */
export function ParseSlashCommand(text: string): $CancellablePromise<[string, string]> {
    return $Call.ByID(3023945064, text);
}

/**
 * ReadFileContent reads a file's content relative to the working directory.
 * Returns the file content as a string. Binary files are detected and skipped.
 * Files larger than maxFileReadSize are truncated.
 */
export function ReadFileContent(relPath: string): $CancellablePromise<string> {
    return $Call.ByID(1751419230, relPath);
}

/**
 * ReloadRules reloads custom rules from disk and updates the agent.
 * Returns the number of rule files loaded and a formatted description.
 */
export function ReloadRules(): $CancellablePromise<[number, string]> {
    return $Call.ByID(472429229);
}

/**
 * SelectProjectDir opens a directory picker and sets the working directory without resetting conversation.
 * If a task is currently active, it also updates the task's working_dir in the database.
 */
export function SelectProjectDir(): $CancellablePromise<string> {
    return $Call.ByID(3629349623);
}

export function SendMessage(prompt: string): $CancellablePromise<void> {
    return $Call.ByID(3096290212, prompt);
}

/**
 * SendMessageWithContext sends a message with file references attached.
 * fileRefsJSON is a JSON array of relative file paths, e.g. ["src/main.go","README.md"].
 * The referenced file contents are read and prepended to the prompt as context.
 */
export function SendMessageWithContext(prompt: string, fileRefsJSON: string): $CancellablePromise<void> {
    return $Call.ByID(3750166975, prompt, fileRefsJSON);
}

/**
 * SetApp sets the application reference (called after app creation).
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3364874960, app);
}

/**
 * SetMode switches the agent between plan and act modes.
 */
export function SetMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(1041154766, mode);
}

/**
 * StartNewConversation resets the conversation and clears the working directory.
 * Used by New Chat button and /newtask to start a completely fresh session.
 */
export function StartNewConversation(): $CancellablePromise<void> {
    return $Call.ByID(2070387902);
}

/**
 * StopMessage aborts the current agent run.
 */
export function StopMessage(): $CancellablePromise<void> {
    return $Call.ByID(2438960290);
}

/**
 * UpdateConfig updates a config key
 */
export function UpdateConfig(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(756022332, key, value);
}

/**
 * WikiIngestFile triggers LLM-based wiki generation for a file.
 * This is completely separate from RAG ingestion and requires a configured LLM provider.
 */
export function WikiIngestFile(filePath: string, kbID: string): $CancellablePromise<void> {
    return $Call.ByID(2380960205, filePath, kbID);
}

// Private type creation functions
const $$createType0 = $models.SlashActionResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.SlashCommandInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = prompts$0.RuleFileInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
const $$createType7 = storage$0.TaskRecord.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = storage$0.MessageRecord.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.DirEntry.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Array($$createType7);
