// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * MessageRecord is the database model for a message.
 */
export class MessageRecord {
    "ID": number;
    "TaskID": string;
    "Role": string;
    "Content": string;
    "ReasoningContent": string;

    /**
     * JSON
     */
    "ToolCalls": string;
    "ToolCallID": string;

    /**
     * JSON - the list of tools available when this message was sent
     */
    "AvailableTools": string;

    /**
     * the tool_choice setting sent with the request (e.g. "required", "auto")
     */
    "ToolChoice": string;
    "CreatedAt": time$0.Time;

    /** Creates a new MessageRecord instance. */
    constructor($$source: Partial<MessageRecord> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("TaskID" in $$source)) {
            this["TaskID"] = "";
        }
        if (!("Role" in $$source)) {
            this["Role"] = "";
        }
        if (!("Content" in $$source)) {
            this["Content"] = "";
        }
        if (!("ReasoningContent" in $$source)) {
            this["ReasoningContent"] = "";
        }
        if (!("ToolCalls" in $$source)) {
            this["ToolCalls"] = "";
        }
        if (!("ToolCallID" in $$source)) {
            this["ToolCallID"] = "";
        }
        if (!("AvailableTools" in $$source)) {
            this["AvailableTools"] = "";
        }
        if (!("ToolChoice" in $$source)) {
            this["ToolChoice"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageRecord {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageRecord($$parsedSource as Partial<MessageRecord>);
    }
}

/**
 * TaskRecord is the database model for a task.
 */
export class TaskRecord {
    "ID": string;
    "Title": string;
    "Prompt": string;
    "Mode": string;
    "Provider": string;
    "Model": string;
    "Status": string;
    "WorkingDir": string;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;
    "CompletedAt": time$0.Time | null;

    /** Creates a new TaskRecord instance. */
    constructor($$source: Partial<TaskRecord> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Prompt" in $$source)) {
            this["Prompt"] = "";
        }
        if (!("Mode" in $$source)) {
            this["Mode"] = "";
        }
        if (!("Provider" in $$source)) {
            this["Provider"] = "";
        }
        if (!("Model" in $$source)) {
            this["Model"] = "";
        }
        if (!("Status" in $$source)) {
            this["Status"] = "";
        }
        if (!("WorkingDir" in $$source)) {
            this["WorkingDir"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }
        if (!("CompletedAt" in $$source)) {
            this["CompletedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskRecord {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskRecord($$parsedSource as Partial<TaskRecord>);
    }
}
